name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Installing dependencies
        run: npm ci
      - name: Lint files
        run: npm run lint
      - name: Building web page
        run: npm run ci-build

      # Only run this if the push is on the master branch

      # - run: echo "speak.exchange" > out/CNAME
      #   if: github.ref == 'refs/heads/master'
      - run: touch out/.nojekyll
        if: github.ref == 'refs/heads/master'
      - name: Add ssh deploy key (for semantic-release)
        env:
          GIT_SSH_COMMAND: 'ssh -o StrictHostKeyChecking=no'
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.GH_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        if: github.ref == 'refs/heads/master'
      - name: Publish to GitHub Pages
        run: npm run publish
        if: github.ref == 'refs/heads/master'
