name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Installing dependencies
      run: npm ci
    - name: Lint files
      run: npm lint
    - name: Building web page
      run: npm run ci-build
